# Name of workflow
name: Node CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: make install

      - name: Run linter
        run: make lint

        name: Test & publish code coverage
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATETESTCOVERAGE }}
        with:
          coverageCommand: make test-coverage
